services:
  n8n:
    container_name: n8n
    profiles: ['n8n']
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Europe/Paris
      - NODE_ENV=development   # optionnel, ou supprime simplement la variable
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_files:/files
    networks:
      - netw
    ports:
      - "5678:5678"

  postgres:
    container_name: postgres
    profiles: ['postgres']
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8npassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netw
    ports:
      - "5432:5432"

  spark:
    container_name: spark
    image: spark:latest
    restart: unless-stopped
    networks:
      - netw
    ports:
      - "8080:8080"
      - "7077:7077"
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master",
        "--host", "0.0.0.0",
        "--port", "7077",
        "--webui-port", "8080"
      ]

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    networks:
      - netw
    volumes:
      - ./notebooks:/home/jovyan/work
    command: >
      start-notebook.sh
      --NotebookApp.token=''


volumes:
  postgres_data:

networks:
  netw:
    external: true
